# Generated by Django 4.1.4 on 2022-12-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_completed_tasks_description_tasks_important_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='important',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
